-- Boomer Engine v4 Build script
-- Written by Tomasz Jonarski (RexDex)

ProjectType("library")

Dependency("base_system")
Dependency("base_memory")
Dependency("base_io")
Dependency("base_containers")
Dependency("base_app")
Dependency("base_graph")
Dependency("base_imgui")
Dependency("base_math")
Dependency("base_reflection")
Dependency("base_object")
Dependency("base_resource")
Dependency("base_script")
Dependency("base_input")
Dependency("base_fibers")
Dependency("base_math")
Dependency("base_image")
