-- Boomer Engine v4 Build script
-- Written by Tomasz Jonarski (RexDex)

ProjectType("library")

Dependency("core_system")
Dependency("core_memory")
Dependency("core_containers")
Dependency("core_fibers")
Dependency("core_test")

FileFilter("src/asyncDispatcherPOSIX.cpp", "posix")
FileFilter("src/asyncDispatcherPOSIX.h", "posix")
FileFilter("src/directoryWatcherPOSIX.cpp", "posix")
FileFilter("src/directoryWatcherPOSIX.h", "posix")
FileFilter("src/fileHandlePOSIX.cpp", "posix")
FileFilter("src/fileHandlePOSIX.h", "posix")
FileFilter("src/fileIteratorPOSIX.cpp", "posix")
FileFilter("src/fileIteratorPOSIX.h", "posix")
FileFilter("src/fileSystemPOSIX.cpp", "posix")
FileFilter("src/fileSystemPOSIX.h", "posix")

FileFilter("src/asyncDispatcherWindows.cpp", "winapi")
FileFilter("src/asyncDispatcherWindows.h", "winapi")
FileFilter("src/directoryWatcherWindows.cpp", "winapi")
FileFilter("src/directoryWatcherWindows.h", "winapi")
FileFilter("src/fileHandleWindows.cpp", "winapi")
FileFilter("src/fileHandleWindows.h", "winapi")
FileFilter("src/fileIteratorWindows.cpp", "winapi")
FileFilter("src/fileIteratorWindows.h", "winapi")
FileFilter("src/fileSystemWindows.cpp", "winapi")
FileFilter("src/fileSystemWindows.h", "winapi")