-- Boomer Engine v4 Build script
-- Written by Tomasz Jonarski (RexDex)

ProjectType("library")

Dependency("base_system")
Dependency("base_memory")
Dependency("base_containers")
Dependency("base_io")
Dependency("base_config")
Dependency("base_object")
Dependency("base_reflection")
Dependency("base_resource")
Dependency("base_xml")
Dependency("base_input")
Dependency("base_image")
Dependency("base_font")
Dependency("base_canvas")
Dependency("base_imgui")
Dependency("base_storage")
Dependency("base_parser")
Dependency("base_graph")
Dependency("base_fibers")
Dependency("base_math")
Dependency("base_app")

FileOption("src/scintilla/Accessor.cxx", "nopch")
FileOption("src/scintilla/AutoComplete.cxx", "nopch")
FileOption("src/scintilla/CallTip.cxx", "nopch")
FileOption("src/scintilla/CaseConvert.cxx", "nopch")
FileOption("src/scintilla/CaseFolder.cxx", "nopch")
FileOption("src/scintilla/Catalogue.cxx", "nopch")
FileOption("src/scintilla/CellBuffer.cxx", "nopch")
FileOption("src/scintilla/CharacterCategory.cxx", "nopch")
FileOption("src/scintilla/CharacterSet.cxx", "nopch")
FileOption("src/scintilla/CharClassify.cxx", "nopch")
FileOption("src/scintilla/ContractionState.cxx", "nopch")
FileOption("src/scintilla/DBCS.cxx", "nopch")
FileOption("src/scintilla/Decoration.cxx", "nopch")
FileOption("src/scintilla/DefaultLexer.cxx", "nopch")
FileOption("src/scintilla/Document.cxx", "nopch")
FileOption("src/scintilla/EditModel.cxx", "nopch")
FileOption("src/scintilla/Editor.cxx", "nopch")
FileOption("src/scintilla/EditView.cxx", "nopch")
FileOption("src/scintilla/ExternalLexer.cxx", "nopch")
FileOption("src/scintilla/Indicator.cxx", "nopch")
FileOption("src/scintilla/KeyMap.cxx", "nopch")
FileOption("src/scintilla/LexCPP.cxx", "nopch")
FileOption("src/scintilla/LexerBase.cxx", "nopch")
FileOption("src/scintilla/LexerModule.cxx", "nopch")
FileOption("src/scintilla/LexerNoExceptions.cxx", "nopch")
FileOption("src/scintilla/LexerSimple.cxx", "nopch")
FileOption("src/scintilla/LexJSON.cxx", "nopch")
FileOption("src/scintilla/LexYAML.cxx", "nopch")
FileOption("src/scintilla/LexLua.cxx", "nopch")
FileOption("src/scintilla/LineMarker.cxx", "nopch")
FileOption("src/scintilla/MarginView.cxx", "nopch")
FileOption("src/scintilla/PerLine.cxx", "nopch")
FileOption("src/scintilla/PositionCache.cxx", "nopch")
FileOption("src/scintilla/PropSetSimple.cxx", "nopch")
FileOption("src/scintilla/RESearch.cxx", "nopch")
FileOption("src/scintilla/RunStyles.cxx", "nopch")
FileOption("src/scintilla/ScintillaBase.cxx", "nopch")
FileOption("src/scintilla/Selection.cxx", "nopch")
FileOption("src/scintilla/Style.cxx", "nopch")
FileOption("src/scintilla/StyleContext.cxx", "nopch")
FileOption("src/scintilla/UniConversion.cxx", "nopch")
FileOption("src/scintilla/ViewStyle.cxx", "nopch")
FileOption("src/scintilla/WordList.cxx", "nopch")
FileOption("src/scintilla/XPM.cxx", "nopch")