-- Boomer Engine v4 Build script
-- Written by Tomasz Jonarski (RexDex)

ProjectType("library")

Dependency("core_system")
Dependency("core_memory")
Dependency("core_containers")
Dependency("core_io")
Dependency("core_config")
Dependency("core_object")
Dependency("core_reflection")
Dependency("core_resource")
Dependency("core_xml")
Dependency("core_input")
Dependency("core_image")
Dependency("core_parser")
Dependency("core_graph")
Dependency("core_fibers")
Dependency("core_math")
Dependency("core_app")

Dependency("engine_font")
Dependency("engine_canvas")
Dependency("engine_imgui")

Dependency("gpu_device")

FileOption("src/scintilla/Accessor.cxx", "nopch")
FileOption("src/scintilla/AutoComplete.cxx", "nopch")
FileOption("src/scintilla/CallTip.cxx", "nopch")
FileOption("src/scintilla/CaseConvert.cxx", "nopch")
FileOption("src/scintilla/CaseFolder.cxx", "nopch")
FileOption("src/scintilla/Catalogue.cxx", "nopch")
FileOption("src/scintilla/CellBuffer.cxx", "nopch")
FileOption("src/scintilla/CharacterCategory.cxx", "nopch")
FileOption("src/scintilla/CharacterSet.cxx", "nopch")
FileOption("src/scintilla/CharClassify.cxx", "nopch")
FileOption("src/scintilla/ContractionState.cxx", "nopch")
FileOption("src/scintilla/DBCS.cxx", "nopch")
FileOption("src/scintilla/Decoration.cxx", "nopch")
FileOption("src/scintilla/DefaultLexer.cxx", "nopch")
FileOption("src/scintilla/Document.cxx", "nopch")
FileOption("src/scintilla/EditModel.cxx", "nopch")
FileOption("src/scintilla/Editor.cxx", "nopch")
FileOption("src/scintilla/EditView.cxx", "nopch")
FileOption("src/scintilla/ExternalLexer.cxx", "nopch")
FileOption("src/scintilla/Indicator.cxx", "nopch")
FileOption("src/scintilla/KeyMap.cxx", "nopch")
FileOption("src/scintilla/LexCPP.cxx", "nopch")
FileOption("src/scintilla/LexerBase.cxx", "nopch")
FileOption("src/scintilla/LexerModule.cxx", "nopch")
FileOption("src/scintilla/LexerNoExceptions.cxx", "nopch")
FileOption("src/scintilla/LexerSimple.cxx", "nopch")
FileOption("src/scintilla/LexJSON.cxx", "nopch")
FileOption("src/scintilla/LexYAML.cxx", "nopch")
FileOption("src/scintilla/LexLua.cxx", "nopch")
FileOption("src/scintilla/LineMarker.cxx", "nopch")
FileOption("src/scintilla/MarginView.cxx", "nopch")
FileOption("src/scintilla/PerLine.cxx", "nopch")
FileOption("src/scintilla/PositionCache.cxx", "nopch")
FileOption("src/scintilla/PropSetSimple.cxx", "nopch")
FileOption("src/scintilla/RESearch.cxx", "nopch")
FileOption("src/scintilla/RunStyles.cxx", "nopch")
FileOption("src/scintilla/ScintillaBase.cxx", "nopch")
FileOption("src/scintilla/Selection.cxx", "nopch")
FileOption("src/scintilla/Style.cxx", "nopch")
FileOption("src/scintilla/StyleContext.cxx", "nopch")
FileOption("src/scintilla/UniConversion.cxx", "nopch")
FileOption("src/scintilla/ViewStyle.cxx", "nopch")
FileOption("src/scintilla/WordList.cxx", "nopch")
FileOption("src/scintilla/XPM.cxx", "nopch")