/***
* Boomer Engine v4
* Written by Tomasz Jonarski (RexDex)
* Source code licensed under LGPL 3.0 license
*
* [# filter: interface #]
***/

#include "build.h"
#include "renderingImageFormat.h"

namespace rendering
{

    //---

    RTTI_BEGIN_TYPE_ENUM(ImageFormat);
        RTTI_ENUM_OPTION(UNKNOWN);
        RTTI_ENUM_OPTION(R8_SNORM);
        RTTI_ENUM_OPTION(R8_UNORM);
        RTTI_ENUM_OPTION(R8_UINT);
        RTTI_ENUM_OPTION(R8_INT);
        RTTI_ENUM_OPTION(RG8_SNORM);
        RTTI_ENUM_OPTION(RG8_UNORM);
        RTTI_ENUM_OPTION(RG8_UINT);
        RTTI_ENUM_OPTION(RG8_INT);
        RTTI_ENUM_OPTION(RGB8_SNORM);
        RTTI_ENUM_OPTION(RGB8_UNORM);
        RTTI_ENUM_OPTION(RGB8_UINT);
        RTTI_ENUM_OPTION(RGB8_INT);
        RTTI_ENUM_OPTION(RGBA8_UNORM);
        RTTI_ENUM_OPTION(RGBA8_SNORM);
        RTTI_ENUM_OPTION(RGBA8_UINT);
        RTTI_ENUM_OPTION(RGBA8_INT);
        RTTI_ENUM_OPTION(BGRA8_UNORM);
        RTTI_ENUM_OPTION(R16F);
        RTTI_ENUM_OPTION(RG16F);
        RTTI_ENUM_OPTION(RGBA16F);
        RTTI_ENUM_OPTION(R32F);
        RTTI_ENUM_OPTION(RG32F);
        RTTI_ENUM_OPTION(RGB32F);
        RTTI_ENUM_OPTION(RGBA32F);
        RTTI_ENUM_OPTION(R16_UNORM);
        RTTI_ENUM_OPTION(R16_SNORM);
        RTTI_ENUM_OPTION(R16_UINT);
        RTTI_ENUM_OPTION(R16_INT);
        RTTI_ENUM_OPTION(RG16_UNORM);
        RTTI_ENUM_OPTION(RG16_SNORM);
        RTTI_ENUM_OPTION(RG16_UINT);
        RTTI_ENUM_OPTION(RG16_INT);
        RTTI_ENUM_OPTION(RGBA16_UNORM);
        RTTI_ENUM_OPTION(RGBA16_SNORM);
        RTTI_ENUM_OPTION(RGBA16_UINT);
        RTTI_ENUM_OPTION(RGBA16_INT);
        RTTI_ENUM_OPTION(R32_UINT);
        RTTI_ENUM_OPTION(R32_INT);
        RTTI_ENUM_OPTION(RG32_UINT);
        RTTI_ENUM_OPTION(RG32_INT);
        RTTI_ENUM_OPTION(RGBA32_UINT);
        RTTI_ENUM_OPTION(RGBA32_INT);
        RTTI_ENUM_OPTION(MAT22F);
        RTTI_ENUM_OPTION(MAT32F);
        RTTI_ENUM_OPTION(MAT33F);
        RTTI_ENUM_OPTION(MAT42F);
        RTTI_ENUM_OPTION(MAT43F);
        RTTI_ENUM_OPTION(MAT44F);
        RTTI_ENUM_OPTION(R11FG11FB10F);
        RTTI_ENUM_OPTION(RGB10_A2_UNORM);
        RTTI_ENUM_OPTION(RGB10_A2_UINT);
        RTTI_ENUM_OPTION(RGBA4_UNORM);
        RTTI_ENUM_OPTION(BC1_UNORM);
        RTTI_ENUM_OPTION(BC2_UNORM);
        RTTI_ENUM_OPTION(BC3_UNORM);
        RTTI_ENUM_OPTION(BC4_UNORM);
        RTTI_ENUM_OPTION(BC5_UNORM);
        RTTI_ENUM_OPTION(BC6_UNSIGNED);
        RTTI_ENUM_OPTION(BC6_SIGNED);
        RTTI_ENUM_OPTION(BC7_UNORM);
        RTTI_ENUM_OPTION(SRGB8);
        RTTI_ENUM_OPTION(SRGBA8);
        RTTI_ENUM_OPTION(BC1_SRGB);
        RTTI_ENUM_OPTION(BC2_SRGB);
        RTTI_ENUM_OPTION(BC3_SRGB);
        RTTI_ENUM_OPTION(BC7_SRGB);
        RTTI_ENUM_OPTION(D24S8);
        RTTI_ENUM_OPTION(D24FS8);
        RTTI_ENUM_OPTION(D32);
    RTTI_END_TYPE();

    //---

} // rendering